[package]
name = "rvariant"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
rkyv = { version = "0.8", features = [], optional = true }
parse_int = "0.9"
chrono = { version = "0.4", features = ["serde"] }